parcellation: aparc+aseg.mgz
skullstrip: brainmask.mgz
hemis_template: ribbon.mgz

atrophy_targets:
- 1030
- 2030
wm_labels:
- 2
- 41
lh_GM_template_labels: 3
lh_WM_template_labels: 2
rh_GM_template_labels: 42
rh_WM_template_labels: 41

n_atrophy_iters: 1
upsampling_factor: 1.0
MSDD: true
RAS: true
